### ISSUE TITLE
pmol to µM calculation not working

### ISSUE THREAD

**Issue by BZHJochen** [luechtian/lipidcountr#1]
![grafik](https://user-images.githubusercontent.com/112397099/187199047-dc9267cd-b0d3-4085-87c8-7c00403e55cd.png)
Hallo, 
der letzte Berechnungsbutton funktioniert in der alpha 2 nicht. Das Workbook hat dann keine Daten.

**Comment by luechtian** [comment]
Sehr cool, dass du GitHub benutzt. Jetzt müssen die Issues nur noch in der richtigen Repo geöffnet werden :)

https://github.com/luechtian/ShinyLipidcountr/issues

**Comment by luechtian** [comment]
Schick mir mal deine textfiles + metadata. Mit meinen Files funktioniert alles.

**Comment by BZHJochen** [comment]
Die anderen 3 Berechnungen macht er. Dachte ich hätte alle samples richtig benannt.
[Daten_Caroline_Pabst.zip](https://github.com/luechtian/lipidcountr/files/9444818/Daten_Caroline_Pabst.zip)

**Comment by luechtian** [comment]
![image](https://user-images.githubusercontent.com/51409126/187214712-8e4575c3-2356-4229-b0f9-51b8c54eda1a.png)
"sample input" muss da stehen, auch nicht in Großbuchstaben.

**Comment by luechtian** [comment]
[Metadata_CarolinePabst_corrected.csv](https://github.com/luechtian/lipidcountr/files/9445056/Metadata_CarolinePabst_corrected.csv)
